### ISSUE TITLE
Failure parsing torrents without trackers

### ISSUE THREAD

**Issue by terorie** [ttlajus/lava_torrent#1]
Parsing a torrent with no trackers created in Transmission/2.94 fails with

> Failed to read torrent: malformed torrent: "announce" does not exist.

[test.torrent.gz](https://github.com/ttlajus/lava_torrent/files/3644259/test.torrent.gz)

As Transmission considers a torrent without trackers valid, parsing should not fail.

**Comment by ttlajus** [comment]
Thank you for reporting this and sorry for the delay.

This sounds like an implementation-dependent detail. [BEP 3](http://bittorrent.org/beps/bep_0003.html) seems to require `announce`, which is why I implemented it this way. But the BitTorrent spec is a mess, so who knows.

I will make `announce` optional. Before that happens, feel free to parse the file as a `BencodeElem` and extract the fields manually.

**Comment by ttlajus** [comment]
Fixed with 223a9b0.

It turned out to be messier than I thought. The tests passed, but now I'm not as sure as before regarding the correctness of code/doc. I'll have to go through everything again eventually, though I'm too busy to do an in-depth check until at least the end of the year.

Thank you again : )

**Comment by terorie** [comment]
Thanks for the quick update, works flawlessly as expected 👍 `lava_torrent` is by far the best torrent file crate right now. I'll keep you updated about any other implementation quirks I might find.

**Comment by ttlajus** [comment]
@terorie You are welcome and thank you for the compliment!

I wrote this crate out of the frustration that there's no good library for extracting torrent information (the good ones are usually full-fledged torrenting library like libtorrent). Never thought anyone else would use it, but I'm glad I'm no longer the only user : )
