### ISSUE TITLE
Allow non absolute paths in `TorrentBuilder`

### ISSUE THREAD

**Issue by Nehliin** [ttlajus/lava_torrent#10]
It's unclear to me why paths must be absolute? It makes it more inconvenient to work with imo but perhaps there is some reasons for this?

**Comment by ttlajus** [comment]
Hi there, it's been almost 5 yrs since I wrote the code, so to be honest I don't remember why I made it this way. If I have to guess it's probably to force the client to double check their input.

Considering that other parts of the library might assume absolute paths, I'd rather not drop this now and risk introducing bugs.

Also, I don't see how getting the absolute path is inconvenient, since it's one call away

```
std::fs::canonicalize(".")
```

**Comment by Nehliin** [comment]
Yeah one can always find the absolute path imo it's inconvenient having to remember to add that manually everywhere since there doesn't seem to be any real reason for not accepting relative paths. But ofc it's up to you, just some feedback for removing papercuts :+1: .

**Comment by ttlajus** [comment]
Changed in `v0.10.0`.

I still think using absolute paths is better though, unless you are dealing with small scripts.
