### ISSUE TITLE
Invalid UTF-8 in Path Name?

### ISSUE THREAD

**Issue by lbfs** [ttlajus/lava_torrent#14]
Greetings,

I've been using your library with great success recently, however there was an issue I ran across that isn't technically a bug? 

There are torrents where the path element is encoded incorrectly. I have two torrents that will not parse correctly due to the path element not being valid UTF-8. It honestly seems like these might be UTF-16 encoded as UTF-8 based on some very quick debugging, although I haven't had time to really understand the issue, throwing these files into online decoders shows a buffer of bytes for these paths instead of the path name. 

Right now the logic is to just throw an error under these cases, is there a way in that these cases the code returns a buffer of bytes rather than a Pathbuf, so that my code could make a "best effort" parsing of the torrent data?

If you look at qBittorrent for example, they seem to be doing extra logic from what I can tell since these will load correctly in the client. 

https://github.com/lbfs/torrent-bootstrap

**Comment by ttlajus** [comment]
Hi, according to [BEP 3](https://www.bittorrent.org/beps/bep_0003.html)

> path - A list of UTF-8 encoded strings corresponding to subdirectory names, the last of which is the actual file name (a zero length list is an error case).

So if a torrent contains non-UTF-8 paths, it is invalid. Whether such torrents should be handled is more of a design decision, and for me the answer would be no.

You have 2 options:

1. Stick with my implementation, call [`BencodeElem::from_file()`](https://docs.rs/lava_torrent/latest/lava_torrent/bencode/enum.BencodeElem.html#method.from_file) on your torrent, manually fix the encodings, and then call [`Torrent::read_from_bytes()`](https://docs.rs/lava_torrent/latest/lava_torrent/torrent/v1/struct.Torrent.html#method.read_from_bytes) to get your torrent.
2. Fork, for each `String::from_utf8()` call in `src/bencode/read.rs`, add a [`String::from_utf16()`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf16) (or whatever decoding method you need) in case of failures, and then use your fork.

**Comment by lbfs** [comment]
I've only seen this in the wild twice and it's very much not the norm and usually with extremely old torrents. 

Your first approach may work well for me, although I would still need to prune those records in post-processing, since I use output paths and the file names would now be mismatched and they need to match what other clients understand. However, this would give me minimal data loss so it would be better than not processing at all. 

Thanks for your time and the provided suggestions, I wasn't sure what the desired behavior for this should be, I'm always for the standard but not everyone adheres to it unfortunately.

**Comment by ttlajus** [comment]
You are welcome.

> I use output paths and the file names would now be mismatched and they need to match what other clients understand.

That's not necessarily the case. I think other clients most likely will normalize strings to UTF-8, so in terms of what they "understand" internally, you should be on the same page.

However, if you are matching on output paths, keep in mind that path encoding is OS-dependent. In Rust, if you want to convert a `PathBuf` to a string of some kind, you get an [`OsString`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.into_os_string) instead of a `String` (which you can still get but the conversion might be [lossy](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.to_string_lossy)).

Does this really matter in practice? Probably not, but it's not as reliable as you'd assume.

Anyways, since you have total control over the bencode items, I would suggest that after fixing the encoding, you save the original path value to an extra metadata field (say, `original_path`). Then `lava_torrent` will put that field into [`File.extra_fields`](https://docs.rs/lava_torrent/latest/lava_torrent/torrent/v1/struct.File.html#structfield.extra_fields). When you do the matching, you can check both `path` and `extra_fields["original_path"]`.
