### ISSUE TITLE
String Unicode normalization breaks pathnames

### ISSUE THREAD

**Issue by Yoitsu** [ttlajus/lava_torrent#9]
https://github.com/ttlajus/lava_torrent/blob/f4ab594f2c32f07a589b49ea480a9a16908036af/src/bencode/read.rs#L186

utf-8 normalization breaks real-world compatibility with most(?) of the bittorrent ecosystem regarding pathnames.

Consider torrent with pathname that can be normalized such as:
[test - パ.zip](https://github.com/ttlajus/lava_torrent/files/10437939/test.-.zip)

combination パ
U+30CF : KATAKANA LETTER HA
U+309A : COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK

can be normalized as パ
U+30D1 : KATAKANA LETTER PA

but it breaks basic operations:
1. create torrent
```sh
mkdir "test - パ"
mktorrent "test - パ"
```
2. check torrent path exists
```rust
let torrent = Torrent::read_from_file("test - パ.torrent").unwrap();
let path = Path::new(&torrent.name);
assert!(path.exists());
```

I tried removing `nfc()` from source code and the snippet works. Is there a reason why utf-8 is normalized by default and could it be optional? Most of the ecosystem does not seem to do normalization (rtorrent, torrentool, mktorrent...)

**Comment by ttlajus** [comment]
Thank you for reporting this and sorry for the delay.

Normalization was done by default because I thought it was a best practice. You can read about it in chapter 17 of [Programming Rust](https://www.oreilly.com/library/view/programming-rust-2nd/9781492052586/).

In retrospect this is a mistake on my end. The decision to normalize should have been left to the client applications.

Fixed in `v0.9.0`.
